# Generated by Django 4.1 on 2023-10-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0002_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="rate",
            name="rate",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
