# Generated by Django 4.1 on 2023-10-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0003_rate_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="QRcode",
            field=models.ImageField(default=0, upload_to="QR"),
            preserve_default=False,
        ),
    ]
